name: oidc connectivity
on:
  push:
    branches:
      - main
  workflow_dispatch:
permissions: write-all
jobs:
oidc_connectivity:
runs-on: ubuntu-latest
steps:
- name: checkout
uses: actions/checkout@v4
- name: Configure AWS Credentials
uses: aws-actions/configure-aws-credentials@v4
with:
role-to-assume: arn:aws:iam::881490097103:role/Ajayrole
aws-region: us-east-1
